"""Bundle export.json + sweep results into a JS file for the portfolio page.

    python scripts/build_site_data.py export.json runs/sweep/results.json out/slm-data.js

Only derives values (perplexity, totals, rounding); never edits measurements.
"""
import json
import math
import sys

import numpy as np

export_path, sweep_path, out_path = sys.argv[1:4]
d = json.load(open(export_path))
import os
d["sweep"] = json.load(open(sweep_path)) if os.path.exists(sweep_path) else None

ids = np.load(f"data/ids_{d['config']['vocab_size']}.npz")
d["tokens_total"] = int(len(ids["train"]) + len(ids["val"]))
d["params_m"] = round(d["params"] / 1e6, 2)
d["initial_val_loss"] = round(d["curve"][0]["val_loss"], 2)
d["ln_vocab"] = round(math.log(d["config"]["vocab_size"]), 2)
d["best_ppl"] = round(math.exp(d["best_val_loss"]), 1)
d["train_minutes"] = round(d["summary"]["seconds"] / 60, 1)
d["best_val_loss"] = round(d["best_val_loss"], 3)

with open(out_path, "w") as f:
    f.write("/* Generated by scripts/build_site_data.py from a real training run. Do not edit. */\n")
    f.write("window.SLM_DATA = ")
    json.dump(d, f, separators=(",", ":"))
    f.write(";\n")
print(f"wrote {out_path}")
